names=['Anil','Ananya','Shashi','Ravikanth']
print(f"{names[0]}, you're invited for dinner")
print(f"{names[1]}, you're invited for dinner")
print(f"{names[2]}, you're invited for dinner")
names.append('Sushma')
print(names)
names.insert(2, 'Vijaya')
print("Here is original Order:")
print(names)
print("\nHere is sorted list:")
print(sorted(names))
print("\nHere is original list list:")
print(names)
names.sort(reverse=True)
print("\nHere is revered order:")
print(names)
print(len(names))